# Generated by Django 5.1.2 on 2024-10-20 04:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_expenses_date_expenses_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensesdetails',
            name='date',
            field=models.DateField(default='2024-10-20'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expensesdetails',
            name='month',
            field=models.CharField(choices=[('janurary', 'January'), ('february', 'February'), ('marth', 'March'), ('april', 'April'), ('may', 'May'), ('june', 'June'), ('july', 'July'), ('august', 'August'), ('september', 'September'), ('october', 'October'), ('november', 'November'), ('december', 'December')], default=datetime.datetime(2024, 10, 20, 4, 47, 45, 906495, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expenses',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('done', 'done')], default='pending', max_length=30),
        ),
    ]
