# Generated by Django 5.1.2 on 2024-11-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_expensesdetails_date_expensesdetails_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='month',
            field=models.CharField(choices=[('janurary', 'January'), ('february', 'February'), ('marth', 'March'), ('april', 'April'), ('may', 'May'), ('june', 'June'), ('july', 'July'), ('august', 'August'), ('september', 'September'), ('october', 'October'), ('november', 'November'), ('december', 'December')], max_length=50),
        ),
        migrations.AlterField(
            model_name='expensesdetails',
            name='month',
            field=models.CharField(choices=[('janurary', 'January'), ('february', 'February'), ('marth', 'March'), ('april', 'April'), ('may', 'May'), ('june', 'June'), ('july', 'July'), ('august', 'August'), ('september', 'September'), ('october', 'October'), ('november', 'November'), ('december', 'December')], max_length=50),
        ),
        migrations.AlterField(
            model_name='incomesource',
            name='income_source',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='incomesource',
            name='month',
            field=models.CharField(choices=[('janurary', 'January'), ('february', 'February'), ('marth', 'March'), ('april', 'April'), ('may', 'May'), ('june', 'June'), ('july', 'July'), ('august', 'August'), ('september', 'September'), ('october', 'October'), ('november', 'November'), ('december', 'December')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
