# Generated by Django 5.1.2 on 2024-11-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_expenses_month_alter_expensesdetails_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='note',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
    ]
