# Generated by Django 5.1.2 on 2024-11-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_expenses_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='note2',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
    ]
