# Generated by Django 5.1.2 on 2024-11-17 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_expenses_note2'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensesdetails',
            name='income_sorce',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses_income_source', to='app.incomesource'),
        ),
    ]
