# Generated by Django 5.1.1 on 2024-12-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_bulkbuyerresvstock_businesstermstable'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensestype',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
