# Generated by Django 5.1.1 on 2024-12-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_expensestype_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensestype',
            name='discription',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
