# Generated by Django 5.1.1 on 2024-12-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_expenses_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensestype',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='month',
            field=models.CharField(choices=[('janurary', 'January'), ('february', 'February'), ('march', 'March'), ('april', 'April'), ('may', 'May'), ('june', 'June'), ('july', 'July'), ('august', 'August'), ('september', 'September'), ('october', 'October'), ('november', 'November'), ('december', 'December')], max_length=50),
        ),
        migrations.AlterField(
            model_name='expensesdetails',
            name='month',
            field=models.CharField(choices=[('janurary', 'January'), ('february', 'February'), ('march', 'March'), ('april', 'April'), ('may', 'May'), ('june', 'June'), ('july', 'July'), ('august', 'August'), ('september', 'September'), ('october', 'October'), ('november', 'November'), ('december', 'December')], max_length=50),
        ),
        migrations.AlterField(
            model_name='incomesource',
            name='month',
            field=models.CharField(choices=[('janurary', 'January'), ('february', 'February'), ('march', 'March'), ('april', 'April'), ('may', 'May'), ('june', 'June'), ('july', 'July'), ('august', 'August'), ('september', 'September'), ('october', 'October'), ('november', 'November'), ('december', 'December')], max_length=50),
        ),
    ]
