# Generated by Django 5.1.2 on 2024-12-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_expensestype_priority_alter_expenses_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensesdetails',
            name='year',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='incomesource',
            name='year',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
